version: '3.8'

services:
  web_flatcargo:
    image: web_flatcargo
    build:
      context: .
    ports:
      - "9460:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - overlay_network

networks:
  overlay_network:
    driver: overlay
    attachable: true
